/* Generated by Cython 0.29.11 */

#ifndef __PYX_HAVE__GodotPython
#define __PYX_HAVE__GodotPython


#ifndef __PYX_HAVE_API__GodotPython

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void gdpython_print_banner(void);

#endif /* !__PYX_HAVE_API__GodotPython */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initGodotPython(void);
#else
PyMODINIT_FUNC PyInit_GodotPython(void);
#endif

#endif /* !__PYX_HAVE__GodotPython */
