  # Generated by PyGodot binding generator
<%!
  from pygodot.binding_generator import python_module_name
%>
##% for class_name, _, _, _, _ in classes:
##from pygodot.cpp.${package}.${python_module_name(class_name)} cimport *
##% endfor
