#!/usr/bin/env python

import os

Import("env")

env.PrependENVPath("PATH", os.getenv("PATH"))

opts = Variables()
cpp_tool = Tool("godotcpp", toolpath=["tools"])
cpp_tool.options(opts, env)
opts.Update(env)

Help(opts.GenerateHelpText(env))

cpp_tool.generate(env)
library = env.GodotCPP()

Return("env")
